name: ci
on:
  push:
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --rm-dist
    - name: Building Docker Image
      env:
        CONTAINER_IMAGE_NAME: pothulapati/kubeker/kubekerd:${{ github.event.number }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com
      run:
        docker build -t $DOCKER_REGISTRY_URL/$CONTAINER_IMAGE_NAME .
    - name: Pushing Image to Github Packages
      uses:  elgohr/Publish-Docker-Github-Action@master
      with:
        name: pothulapati/kubeker/kubekerd:${{ github.event.number }}
        username: ${{secrets.GITHUB_PKG_REGISTRY_USERNAME}}
        password: ${{secrets.GITHUB_PKG_REGISTRY_PASSWORD}}
        registry: docker.pkg.github.com
    - name: Uploading Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: gorelease-outputs
        path: dist